<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categorys = [
            [
                'category' => 'islamic',
                'name' => 'Islamic',
                'description' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
            ],
            [
                'category' => 'news-dh',
                'name' => 'Nwes DH',
                'description' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
            ],
            [
                'category' => 'story-dh',
                'name' => 'Story DH',
                'description' => 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
            ],
            [
                'category' => 'khusus-1-165',
                'name' => 'Eksekutif',
                'description' => 'Untuk profil pimpinan'
            ],
            [
                'category' => 'khusus-2-165',
                'name' => 'Hard and Soft Skill',
                'description' => 'Hard and Soft Skill',
            ],
            [
                'category' => 'khusus-umum-165',
                'name' => 'Default',
                'description' => 'Tampilan umum namun kategori khusus karena bawaan Aplikasi'
            ]
        ];

        $isiblogs = [
            [
                'category_id' => 1,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'metode-hisab-penentuan-1-syawal',
                'title' => 'Metode Hisab, Penentuan 1 Syawal',
                'excerpt' => 'Metode Hisab, Penentuan 1 Syawal',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'tasyakkur-ke-56-darul-huffadh-cetak-puluhan-kader-ummat',
                'title' => 'Tasyakkur ke 56, Darul Huffadh cetak puluhan kader Ummat',
                'excerpt' => 'Tasyakkur ke 56, Darul Huffadh cetak puluhan kader Ummat',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'ke-darul-huffadh-untuk-apa?',
                'title' => 'Ke Darul Huffadh, Untuk apa?',
                'excerpt' => 'Ke Darul Huffadh, Untuk apa?',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'profil-pendiri-kh-lanre-said',
                'title' => 'Profil Pendiri Darul Huffadh 77',
                'excerpt' => 'KH. Lanre Said',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/pendiri-kh-lanre-said.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'profil-pimpinan-ust-saad-said',
                'title' => 'Profil Pimpinan Darul Huffadh 77',
                'excerpt' => 'Ust. Saad Said',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/pimpinan-ust-saad-said.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'profil-direktur-putra',
                'title' => 'Profil Direktur Putra Darul Huffadh 77',
                'excerpt' => 'Ust. Mustari Gaffar, S.Pd.I',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/direktur-putra.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 4,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'profil-direktur-putri',
                'title' => 'Profil Direktur Putri Darul Huffadh 77',
                'excerpt' => 'Usth. Saddiyah Said',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/direktur-putri.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 0,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'kulliyatul-muallimin-alislamiyah',
                'title' => 'Kulliyatul Muallimin Alislamiyah, Darul Huffadh 77',
                'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate odit sapiente voluptatum provident asperiores, commodi eos! Commodi iusto obcaecati ut mollitia, eveniet quidem iste maiores, veritatis et amet officia? Totam?',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'tahfidzhul-quran',
                'title' => 'Program Tahfidzh, Darul Huffadh 77',
                'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate odit sapiente',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'pengabdian',
                'title' => 'Pendidikan is pengabdian',
                'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate odit sapiente',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'osdha',
                'title' => 'OSDHA',
                'excerpt' => 'Organisai Santri Darul Huffadh 77',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'persidha',
                'title' => 'PERSIDHA',
                'excerpt' => 'Persatuan Silat Darul Huffadh 77',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'pramuka',
                'title' => 'PRAMUKA',
                'excerpt' => 'Pondok Pesantren Darul Huffadh 77',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'slug' => 'djour',
                'title' => 'D`Jour',
                'excerpt' => 'Pondok Pesantren Darul Huffadh 77',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 5,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'title' => 'SENI',
                'slug' => 'seni',
                'excerpt' => 'Pondok Pesantren Darul Huffadh 77',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'title' => 'Sejarah Pendirian Maahad',
                'slug' => 'sejarah-pendirian-maahad',
                'excerpt' => 'Pondok Pesantren Darul Huffadh 77',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'title' => 'Sejarah Pondok Lama',
                'slug' => 'sejarah-pondok-lama',
                'excerpt' => 'Pondok Pesantren Darul Huffadh 77',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'title' => 'Sejarah Pondok Baru',
                'slug' => 'sejarah-pondok-baru',
                'excerpt' => 'Pondok Pesantren Darul Huffadh 77',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'title' => 'Darul Huffadh Milik Seluruh Ummat Muslimin !',
                'slug' => 'darul-huffadh-milik-seluruh-ummat-muslimin',
                'excerpt' => 'Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit.',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 6,
                'user_id' => 1,
                'oleh' => 'Khaeril Maswal Zaid',
                'title' => 'Sepenuhnya ditanggung, Belajar di Darul Huffadh tanpa biaya apapun.',
                'slug' => 'sepenuhnya-ditanggung-bBelajar-di-darul-huffadh-tanpa-biaya-apapun',
                'excerpt' => 'Eirmod sed tempor lorem ut dolores. Aliquyam sit sadipscing kasd ipsum. Dolor ea et dolore et at sea ea at dolor, justo ipsum duo rebum sea invidunt voluptua.',
                'body1' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'body2' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis commodi, ratione soluta, accusamus beatae quidem nesciunt doloribus consequatur animi veritatis molestias atque. Cumque adipisci inventore totam reprehenderit ratione molestiae magnam? Libero ipsam qui rem deleniti explicabo vel commodi molestias reiciendis expedita aliquam asperiores nihil quibusdam eveniet voluptates iure cum illo molestiae repudiandae in perspiciatis, voluptate hic culpa? Accusantium repellat nihil voluptate est, beatae facere eveniet temporibus.</p><p>Quisquam, consequuntur optio consectetur illum neque id nihil? Explicabo, magni autem labore eum fuga molestias amet numquam possimus! Beatae est ullam, facilis numquam consequatur, quasi deleniti iusto dolorem voluptatem iste impedit officia sequi veniam distinctio, recusandae laboriosam autem labore incidunt a. Ipsum, exercitationem dolor! Rerum praesentium, voluptatibus nostrum aliquam id fuga necessitatibus quasi reiciendis nisi recusandae. Iure fuga magnam nesciunt placeat, eum provident alias fugiat natus dolores.</p>',
                'picture1' => 'blog/blog-1.jpg',
                'picture2' => 'blog/blog-2.jpg',
                'picture3' => 'blog/blog-3.jpg',
                'album' => 1,
                'visit' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($categorys as $category) {
            DB::table('blog_categories')->insert($category);
        }

        foreach ($isiblogs as $isiblog) {
            DB::table('blogs')->insert($isiblog);
        }

        //Run : php artisan db:seed --class=BlogSeeder
    }
}
